/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'Europe/Paris' | 'UTC';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    sites: Site;
    users: User;
    pages: Page;
    media: Media;
    categories: Category;
    products: Product;
    'order-sequences': OrderSequence;
    orders: Order;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    sites: SitesSelect<false> | SitesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'order-sequences': OrderSequencesSelect<false> | OrderSequencesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  name: string;
  /**
   * Identifiant technique du site. En dev, le domaine local sera {slug}.localhost.
   */
  slug: string;
  /**
   * Domaine custom en production (ex. pizzeria-mamma.fr). Optionnel en dev : si vide, {slug}.localhost est utilisé.
   */
  domain?: string | null;
  contact?: {
    email?: string | null;
    phone?: string | null;
    street?: string | null;
    postalCode?: string | null;
    city?: string | null;
  };
  schedule?: {
    /**
     * Midi et soir pour chaque jour. Les horaires restaurant sont indicatifs ; les créneaux click & collect pilotent les commandes.
     */
    weeklyHours?: {
      mondayLunch?: {
        closed?: boolean | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantOpen?: string | null;
        /**
         * Format 24h (ex. 11:45).
         */
        firstPickupSlot?: string | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantClose?: string | null;
        /**
         * Format 24h (ex. 13:30).
         */
        lastPickupSlot?: string | null;
        id?: string | null;
      };
      mondayEvening?: {
        closed?: boolean | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantOpen?: string | null;
        /**
         * Format 24h (ex. 11:45).
         */
        firstPickupSlot?: string | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantClose?: string | null;
        /**
         * Format 24h (ex. 13:30).
         */
        lastPickupSlot?: string | null;
        id?: string | null;
      };
      tuesdayLunch?: {
        closed?: boolean | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantOpen?: string | null;
        /**
         * Format 24h (ex. 11:45).
         */
        firstPickupSlot?: string | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantClose?: string | null;
        /**
         * Format 24h (ex. 13:30).
         */
        lastPickupSlot?: string | null;
        id?: string | null;
      };
      tuesdayEvening?: {
        closed?: boolean | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantOpen?: string | null;
        /**
         * Format 24h (ex. 11:45).
         */
        firstPickupSlot?: string | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantClose?: string | null;
        /**
         * Format 24h (ex. 13:30).
         */
        lastPickupSlot?: string | null;
        id?: string | null;
      };
      wednesdayLunch?: {
        closed?: boolean | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantOpen?: string | null;
        /**
         * Format 24h (ex. 11:45).
         */
        firstPickupSlot?: string | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantClose?: string | null;
        /**
         * Format 24h (ex. 13:30).
         */
        lastPickupSlot?: string | null;
        id?: string | null;
      };
      wednesdayEvening?: {
        closed?: boolean | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantOpen?: string | null;
        /**
         * Format 24h (ex. 11:45).
         */
        firstPickupSlot?: string | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantClose?: string | null;
        /**
         * Format 24h (ex. 13:30).
         */
        lastPickupSlot?: string | null;
        id?: string | null;
      };
      thursdayLunch?: {
        closed?: boolean | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantOpen?: string | null;
        /**
         * Format 24h (ex. 11:45).
         */
        firstPickupSlot?: string | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantClose?: string | null;
        /**
         * Format 24h (ex. 13:30).
         */
        lastPickupSlot?: string | null;
        id?: string | null;
      };
      thursdayEvening?: {
        closed?: boolean | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantOpen?: string | null;
        /**
         * Format 24h (ex. 11:45).
         */
        firstPickupSlot?: string | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantClose?: string | null;
        /**
         * Format 24h (ex. 13:30).
         */
        lastPickupSlot?: string | null;
        id?: string | null;
      };
      fridayLunch?: {
        closed?: boolean | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantOpen?: string | null;
        /**
         * Format 24h (ex. 11:45).
         */
        firstPickupSlot?: string | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantClose?: string | null;
        /**
         * Format 24h (ex. 13:30).
         */
        lastPickupSlot?: string | null;
        id?: string | null;
      };
      fridayEvening?: {
        closed?: boolean | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantOpen?: string | null;
        /**
         * Format 24h (ex. 11:45).
         */
        firstPickupSlot?: string | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantClose?: string | null;
        /**
         * Format 24h (ex. 13:30).
         */
        lastPickupSlot?: string | null;
        id?: string | null;
      };
      saturdayLunch?: {
        closed?: boolean | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantOpen?: string | null;
        /**
         * Format 24h (ex. 11:45).
         */
        firstPickupSlot?: string | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantClose?: string | null;
        /**
         * Format 24h (ex. 13:30).
         */
        lastPickupSlot?: string | null;
        id?: string | null;
      };
      saturdayEvening?: {
        closed?: boolean | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantOpen?: string | null;
        /**
         * Format 24h (ex. 11:45).
         */
        firstPickupSlot?: string | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantClose?: string | null;
        /**
         * Format 24h (ex. 13:30).
         */
        lastPickupSlot?: string | null;
        id?: string | null;
      };
      sundayLunch?: {
        closed?: boolean | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantOpen?: string | null;
        /**
         * Format 24h (ex. 11:45).
         */
        firstPickupSlot?: string | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantClose?: string | null;
        /**
         * Format 24h (ex. 13:30).
         */
        lastPickupSlot?: string | null;
        id?: string | null;
      };
      sundayEvening?: {
        closed?: boolean | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantOpen?: string | null;
        /**
         * Format 24h (ex. 11:45).
         */
        firstPickupSlot?: string | null;
        /**
         * Indicatif — affiché au client, ne pilote pas les créneaux.
         */
        restaurantClose?: string | null;
        /**
         * Format 24h (ex. 13:30).
         */
        lastPickupSlot?: string | null;
        id?: string | null;
      };
    };
    /**
     * Fermetures ou horaires spéciaux (Noël, congés…). Pas de jours fériés automatiques.
     */
    exceptions?:
      | {
          startDate: string;
          /**
           * Laisser vide pour un jour unique.
           */
          endDate?: string | null;
          type: 'closed' | 'custom_hours';
          label?: string | null;
          /**
           * Affiché sur la carte / commande si ce jour est concerné.
           */
          note?: string | null;
          /**
           * Même structure que les horaires hebdomadaires (midi / soir).
           */
          periods?:
            | {
                closed?: boolean | null;
                /**
                 * Indicatif — affiché au client, ne pilote pas les créneaux.
                 */
                restaurantOpen?: string | null;
                /**
                 * Format 24h (ex. 11:45).
                 */
                firstPickupSlot?: string | null;
                /**
                 * Indicatif — affiché au client, ne pilote pas les créneaux.
                 */
                restaurantClose?: string | null;
                /**
                 * Format 24h (ex. 13:30).
                 */
                lastPickupSlot?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  clickAndCollect?: {
    /**
     * Coupe ou rouvre le click & collect immédiatement, indépendamment des créneaux.
     */
    manualStatus?: ('auto' | 'open' | 'closed') | null;
    slotDurationMinutes?: ('15' | '30' | '45' | '60') | null;
    /**
     * Optionnel. Limite le nombre de commandes par créneau de retrait.
     */
    maxOrdersPerSlot?: number | null;
    tracking?: {
      showPickupSlot?: boolean | null;
      showCountdown?: boolean | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  /**
   * Sites accessibles pour cet utilisateur.
   */
  sites?: (number | Site)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  site?: (number | null) | Site;
  title: string;
  slug: string;
  layout: (
    | {
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'simpleText';
      }
    | {
        paragraph: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'simpleParagraph';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'formattedText';
      }
    | {
        image: number | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'image';
      }
    | {
        items: {
          fieldType: 'text' | 'textarea';
          textValue?: string | null;
          textareaValue?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'conditionalRepeater';
      }
    | {
        images: (number | Media)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'gallery';
      }
  )[];
  seoMetaTitle?: string | null;
  seoMetaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  site?: (number | null) | Site;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  site?: (number | null) | Site;
  name: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  site?: (number | null) | Site;
  name: string;
  slug: string;
  price: number;
  /**
   * Ingrédients ou précisions affichées sur la carte.
   */
  description?: string | null;
  /**
   * Catégories réutilisables (produits, blog, etc.).
   */
  categories?: (number | Category)[] | null;
  featuredImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Compteur interne par site pour les numéros de commande.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-sequences".
 */
export interface OrderSequence {
  id: number;
  site: number | Site;
  nextNumber: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  site: number | Site;
  orderNumber: number;
  status: 'in_progress' | 'completed' | 'cancelled';
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refunded';
  customer: {
    name: string;
    email: string;
    phone: string;
  };
  pickupSlot: {
    value: string;
    date: string;
    time: string;
  };
  lines: {
    product?: (number | null) | Product;
    name: string;
    price: number;
    quantity: number;
    id?: string | null;
  }[];
  total: number;
  trackingToken: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'order-sequences';
        value: number | OrderSequence;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        street?: T;
        postalCode?: T;
        city?: T;
      };
  schedule?:
    | T
    | {
        weeklyHours?:
          | T
          | {
              mondayLunch?:
                | T
                | {
                    closed?: T;
                    restaurantOpen?: T;
                    firstPickupSlot?: T;
                    restaurantClose?: T;
                    lastPickupSlot?: T;
                    id?: T;
                  };
              mondayEvening?:
                | T
                | {
                    closed?: T;
                    restaurantOpen?: T;
                    firstPickupSlot?: T;
                    restaurantClose?: T;
                    lastPickupSlot?: T;
                    id?: T;
                  };
              tuesdayLunch?:
                | T
                | {
                    closed?: T;
                    restaurantOpen?: T;
                    firstPickupSlot?: T;
                    restaurantClose?: T;
                    lastPickupSlot?: T;
                    id?: T;
                  };
              tuesdayEvening?:
                | T
                | {
                    closed?: T;
                    restaurantOpen?: T;
                    firstPickupSlot?: T;
                    restaurantClose?: T;
                    lastPickupSlot?: T;
                    id?: T;
                  };
              wednesdayLunch?:
                | T
                | {
                    closed?: T;
                    restaurantOpen?: T;
                    firstPickupSlot?: T;
                    restaurantClose?: T;
                    lastPickupSlot?: T;
                    id?: T;
                  };
              wednesdayEvening?:
                | T
                | {
                    closed?: T;
                    restaurantOpen?: T;
                    firstPickupSlot?: T;
                    restaurantClose?: T;
                    lastPickupSlot?: T;
                    id?: T;
                  };
              thursdayLunch?:
                | T
                | {
                    closed?: T;
                    restaurantOpen?: T;
                    firstPickupSlot?: T;
                    restaurantClose?: T;
                    lastPickupSlot?: T;
                    id?: T;
                  };
              thursdayEvening?:
                | T
                | {
                    closed?: T;
                    restaurantOpen?: T;
                    firstPickupSlot?: T;
                    restaurantClose?: T;
                    lastPickupSlot?: T;
                    id?: T;
                  };
              fridayLunch?:
                | T
                | {
                    closed?: T;
                    restaurantOpen?: T;
                    firstPickupSlot?: T;
                    restaurantClose?: T;
                    lastPickupSlot?: T;
                    id?: T;
                  };
              fridayEvening?:
                | T
                | {
                    closed?: T;
                    restaurantOpen?: T;
                    firstPickupSlot?: T;
                    restaurantClose?: T;
                    lastPickupSlot?: T;
                    id?: T;
                  };
              saturdayLunch?:
                | T
                | {
                    closed?: T;
                    restaurantOpen?: T;
                    firstPickupSlot?: T;
                    restaurantClose?: T;
                    lastPickupSlot?: T;
                    id?: T;
                  };
              saturdayEvening?:
                | T
                | {
                    closed?: T;
                    restaurantOpen?: T;
                    firstPickupSlot?: T;
                    restaurantClose?: T;
                    lastPickupSlot?: T;
                    id?: T;
                  };
              sundayLunch?:
                | T
                | {
                    closed?: T;
                    restaurantOpen?: T;
                    firstPickupSlot?: T;
                    restaurantClose?: T;
                    lastPickupSlot?: T;
                    id?: T;
                  };
              sundayEvening?:
                | T
                | {
                    closed?: T;
                    restaurantOpen?: T;
                    firstPickupSlot?: T;
                    restaurantClose?: T;
                    lastPickupSlot?: T;
                    id?: T;
                  };
            };
        exceptions?:
          | T
          | {
              startDate?: T;
              endDate?: T;
              type?: T;
              label?: T;
              note?: T;
              periods?:
                | T
                | {
                    closed?: T;
                    restaurantOpen?: T;
                    firstPickupSlot?: T;
                    restaurantClose?: T;
                    lastPickupSlot?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  clickAndCollect?:
    | T
    | {
        manualStatus?: T;
        slotDurationMinutes?: T;
        maxOrdersPerSlot?: T;
        tracking?:
          | T
          | {
              showPickupSlot?: T;
              showCountdown?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  sites?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        simpleText?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        simpleParagraph?:
          | T
          | {
              paragraph?: T;
              id?: T;
              blockName?: T;
            };
        formattedText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              id?: T;
              blockName?: T;
            };
        conditionalRepeater?:
          | T
          | {
              items?:
                | T
                | {
                    fieldType?: T;
                    textValue?: T;
                    textareaValue?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?: T;
              id?: T;
              blockName?: T;
            };
      };
  seoMetaTitle?: T;
  seoMetaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  site?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  slug?: T;
  price?: T;
  description?: T;
  categories?: T;
  featuredImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-sequences_select".
 */
export interface OrderSequencesSelect<T extends boolean = true> {
  site?: T;
  nextNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  site?: T;
  orderNumber?: T;
  status?: T;
  paymentStatus?: T;
  customer?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  pickupSlot?:
    | T
    | {
        value?: T;
        date?: T;
        time?: T;
      };
  lines?:
    | T
    | {
        product?: T;
        name?: T;
        price?: T;
        quantity?: T;
        id?: T;
      };
  total?: T;
  trackingToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}